version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/ASSIGNMENT/src
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - project

  database:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - project

networks:
  project:
